
# ... general stuff - keep here, and only add the below to your configuration.yaml

input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actionable notifications skill. Did it work?", "event": "actionable.skill.test"}'

script:
  activate_alexa_actionable_notification:
    alias: activate_alexa_actionable_notification
    description: Activates an actionable notification on a specific echo device
    fields:
      text:
        description: The text you would like alexa to speak.
        example: 'What would you like the thermostat set to?'
      event_id:
        description: Correlation ID for event responses
        example: 'ask_for_temperature'
      alexa_device:
        description: Alexa device you want to trigger
        example: 'media_player.bedroom_echo'
      suppress_confirmation:
        description: Set true if you want to suppress 'okay' confirmation
        example: 'true'
      confirmation_text:
          description: The message Alexa should say after the user responds
          example: "Okay,I set the temperature"
    sequence:
      - action: input_text.set_value
        target:
          entity_id: input_text.alexa_actionable_notification
        data_template:
          value: '{"text": "{{ text }}", "event": "{{ event_id }}", "suppress_confirmation": "{{ suppress_confirmation }}", "confirmation_text": "{{ confirmation_text }}"}'
      - action: media_player.play_media
        target:
          entity_id: "{{ alexa_device }}"
        data_template:
          media_content_type: skill
          media_content_id:  <Your Skill ID>
    mode: single