name: Build Linux

on:
  release:
    types: [created]

permissions:
      contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install zip gzip tar

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip

      - name: Install requirements to lambda folder
        run: pip install -r requirements.txt -t lambda/

      - name: Zip Lambda fodler
        run: zip -r alexa-actions-linux.zip lambda

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: alexa-actions-linux.zip
          asset_name: AlexaActionsLinux.zip
          asset_content_type: application/zip
